### ISSUE TITLE
Fix metadata for social / slack unfurl

### ISSUE THREAD

**Issue by ryanlabouve** [startupdotdev/sd-web#1]
<img width="605" alt="Slack | the-daily-report | startup dev 2022-01-31 14-22-38" src="https://user-images.githubusercontent.com/1318878/151867104-3610bf24-9ea9-45f6-ab0d-b9ac21ee1cb1.png">

**Comment by johnmosesman** [comment]
We have some metadata now 
<img width="518" alt="image" src="https://user-images.githubusercontent.com/3760568/155792144-28562eba-cdf0-466d-a8dd-8fd582c8cc94.png">
